Delete region logic md and update read me to go to the paper mc website
PaperMC/Folia pull request #33
Opened 2023-04-03 03:39 UTC by ShoelessTom

2023-04-04 01:19 UTC, Spottedleaf requested changes

2023-04-04 01:19 UTC, Spottedleaf commented on REGION_LOGIC.md
People may be directly linking to the REGION_LOGIC.md file, so it should stay as a redirection.

2023-04-04 01:19 UTC, Spottedleaf commented on README.md
This is fine

2023-04-08 00:59 UTC, ShoelessTom commented
yes i agree

2023-04-08 01:00 UTC, closed without merging